SQLALCHEMY_DATABASE_URI = "sqlite:///temp-database.db"
SECRET_KEY = "secret key"
JWT_EXPIRATION_DELTA = 7
ENV = "DEVELOPMENT"
MAIL_SERVER = "www.accesstt.com"
MAIL_PORT = 465
MAIL_USERNAME = "info2601@accesstt.com"
MAIL_PASSWORD = "2ajE+7R5Us$_"
MAIL_USE_TLS = False
MAIL_USE_SSL = True